### PR TITLE
Properly encode filename in urls

### LINKED ISSUE #58: Cannot open files with ampersand in path
**Describe the bug**
Error when trying to open a file that has an ampersand in the path (either folder or filename). Error message shows the path truncated at the ampersand.

**To Reproduce**
1. Create a document, spreadsheet, or presentation with an ampersand in the name (or in a folder with an ampersand)
2. Click the file to open in Office Online
3. Error message in the editor window, showing path cut off

**Expected behavior**
File opens in the Office Online editor

**Client details:**
 - OS: Windows 10
 - Browser: Firefox 78esr, Chrome 87
 - Device: Desktop

## Server details

**Operating system**: CentOS 7

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.4.13

**Nextcloud version:** 20.0.2.2

**Version of the officeonline app** 1.0.1

**Version of Office Online server** 16.0.10338.20039

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
{
	"reqId": "O5xd6R67XRmvvRZxD4Sd",
	"level": 0,
	"time": "2020-12-07T17:16:50+00:00",
	"remoteAddr": "10.0.3.8",
	"user": "admin",
	"app": "officeonline",
	"method": "PROPFIND",
	"url": "/remote.php/dav/files/admin/Test%20%26%20troubleshoot/TestDoc.docx",
	"message": "/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.",
	"userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0",
	"version": "20.0.2.2"
}{
	"reqId": "3GQMF5CBs2Fb3i2aHAkH",
	"level": 0,
	"time": "2020-12-07T17:16:51+00:00",
	"remoteAddr": "10.0.3.8",
	"user": "admin",
	"app": "officeonline",
	"method": "GET",
	"url": "/apps/officeonline/index?fileId=3176297&requesttoken=TOKEN&path=/Test%20&%20troubleshoot/TestDoc.docx",
	"message": "/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.",
	"userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0",
	"version": "20.0.2.2"
}{
	"reqId": "3GQMF5CBs2Fb3i2aHAkH",
	"level": 3,
	"time": "2020-12-07T17:16:51+00:00",
	"remoteAddr": "10.0.3.8",
	"user": "admin",
	"app": "officeonline",
	"method": "GET",
	"url": "/apps/officeonline/index?fileId=3176297&requesttoken=TOKEN&path=/Test%20&%20troubleshoot/TestDoc.docx",
	"message": {
		"Exception": "OCP\\Files\\NotFoundException",
		"Message": "/admin/files/Test ",
		"Code": 0,
		"Trace": [{
				"file": "/var/www/html/lib/private/Files/Node/Folder.php",
				"line": 140,
				"function": "get",
				"class": "OC\\Files\\Node\\Root",
				"type": "->",
				"args": ["/admin/files/Test "]
			}, {
				"file": "/var/www/html/custom_apps/officeonline/lib/Controller/DocumentController.php",
				"line": 228,
				"function": "get",
				"class": "OC\\Files\\Node\\Folder",
				"type": "->",
				"args": ["/Test "]
			}, {
				"file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
				"line": 169,
				"function": "index",
				"class": "OCA\\Officeonline\\Controller\\DocumentController",
				"type": "->",
				"args": ["3176297", "/Test "]
			}, {
				"file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
				"line": 100,
				"function": "executeController",
				"class": "OC\\AppFramework\\Http\\Dispatcher",
				"type": "->",
				"args": [{
						"__class__": "OCA\\Officeonline\\Controller\\DocumentController"
					}, "index"]
			}, {
				"file": "/var/www/html/lib/private/AppFramework/App.php",
				"line": 152,
				"function": "dispatch",
				"class": "OC\\AppFramework\\Http\\Dispatcher",
				"type": "->",
				"args": [{
						"__class__": "OCA\\Officeonline\\Controller\\DocumentController"
					}, "index"]
			}, {
				"file": "/var/www/html/lib/private/Route/Router.php",
				"line": 308,
				"function": "main",
				"class": "OC\\AppFramework\\App",
				"type": "::",
				"args": ["OCA\\Officeonline\\Controller\\DocumentController", "index", {
						"__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
					}, {
						"action": null,
						"_route": "officeonline.document.index"
					}
				]
			}, {
				"file": "/var/www/html/lib/base.php",
				"line": 1008,
				"function": "match",
				"class": "OC\\Route\\Router",
				"type": "->",
				"args": ["/apps/officeonline/index"]
			}, {
				"file": "/var/www/html/index.php",
				"line": 37,
				"function": "handleRequest",
				"class": "OC",
				"type": "::",
				"args": []
			}
		],
		"File": "/var/www/html/lib/private/Files/Node/Root.php",
		"Line": 205,
		"CustomMessage": "--"
	},
	"userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0",
	"version": "20.0.2.2"
}
```

#### Browser log
```
Here are the network requests made by the browser:

PROPFIND http://server.name/remote.php/dav/files/admin/Test%20%26%20troubleshoot/TestDoc.docx
GET http://server.name/apps/officeonline/index?fileId=3176297&requesttoken=TOKEN&path=/Test%20&%20troubleshoot/TestDoc.docx
```

</details>

### PR DESCRIPTION
**Pull request by juliushaertl**
Fixes #58 

Replaces #62

### CODE REVIEW

File: src/view/Office.vue [hunk 1]
```diff
@@ -113,11 +113,11 @@ export default {
 			const dir = document.getElementById('dir')
 			let documentUrl = ''
 			if (sharingToken && dir.value === '') {
-				documentUrl = getDocumentUrlForPublicFile(this.filename)
+				documentUrl = getDocumentUrlForPublicFile(encodeURIComponent(this.filename))
```
Comment (ChristophWurst) [inline src/view/Office.vue:116]: can we put it into the helper?

Comment (juliushaertl) [reply src/view/Office.vue]: Done
